# Generated by Django 4.2.28 on 2026-03-02 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profesores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ramo', models.CharField(max_length=100)),
                ('nivel', models.CharField(choices=[('Primero Medio', '1° Medio'), ('Segundo Medio', '2° Medio'), ('Tercero Medio', '3° Medio'), ('Cuarto Medio', '4° Medio')], max_length=50)),
                ('jornada', models.CharField(choices=[('Mañana', 'Mañana (08:00 - 14:00)'), ('Tarde', 'Tarde (14:00 - 20:00)'), ('Completa', 'Jornada Completa')], max_length=50)),
                ('profesor_jefe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_a_cargo', to='profesores.profesor')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['nivel', 'nombre_ramo'],
            },
        ),
    ]
