# Generated by Django 4.2.28 on 2026-03-02 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('curso', models.CharField(default='Sin asignar', max_length=10)),
                ('promedio', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
